### ISSUE TITLE
README should contain repository data, not the Summary of the project

### ISSUE THREAD

**Issue by AliciaMstt** [Duhyadi/Tareas_BioinfRepro2019_DOG#2]
Your README is well written, but currently it looks more like the summary of the project instead of a README.

Remember a README should clearly state:

* General organization of the project directory (short description of each directory within) 
* Where you got the data from
* What you did (name of the analysis) 
* With which script
* Path to each script
l organization of the project directory (short description of each directory within) 
* What you did (name of the analysis) 
* With which script
* Path to each script

**Comment by Duhyadi** [comment]
Understood thank you very much
